major:
mparticle-integrations/mparticle-javascript-integration-appboy pull request #56
Opened 2022-03-17 15:46 UTC by rmi22186

# Summary

This PR updates the Braze SDK to 3.5.0, which includes breaking changes from Braze's end.

Due to these [breaking changes](https://www.braze.com/docs/developer_guide/platform_integration_guides/web/changelog/#300), we are sending customer comms to ensure our customers are aware of what they have to do if they are using any Braze SDK methods directly.  We will not release this until ~1 month after customer comms have been made available to give customers time to address any potential breaking changes in their code.

2022-03-17 19:22 UTC, alexs-mparticle requested changes

2022-03-17 19:22 UTC, alexs-mparticle commented on src/AppboyKit-dev.js
> +            if (shouldDisplay) {
On line 318, you're initializing `shouldDisplay` as `true` but right after you're checking if `inAppMessage` is `instanceof appboy.InAppMessage`. What happens if `inAppMessage` fails the check on line 320?

I would add a small comment somewhere at the top of the function explaining what why `shouldDisplay` should start as true.

2022-03-17 19:24 UTC, rmi22186 commented on src/AppboyKit-dev.js
> +            if (shouldDisplay) {
This entire code block is pulled from Braze's docs as a best practice code snippet, so I didn't make any decisions here.

2022-03-17 19:28 UTC, alexs-mparticle commented on src/AppboyKit-dev.js
> +            if (shouldDisplay) {
Disregard then.

2022-03-17 19:28 UTC, alexs-mparticle approved these changes

2022-03-17 19:33 UTC, alexs-mparticle approved these changes

2022-03-22 17:52 UTC, davidbielik commented
We've added a new method to track 3rd party integrations. Could you please add this line just after calling `appboy.initialize`:

```
appboy.addSdkMetadata(['mp']);
```

if you have a way to differentiate between CDN vs. NPM, let me know and we can add those values in as well.

2022-03-22 19:09 UTC, davidbielik commented on src/AppboyKit-dev.js
>      function primeAppBoyWebPush() {
@rmi22186

2022-03-22 19:31 UTC, rmi22186 commented on src/AppboyKit-dev.js
>      function primeAppBoyWebPush() {
This function is called after we [initialize Braze](https://github.com/mparticle-integrations/mparticle-javascript-integration-appboy/blob/master/src/AppboyKit-dev.js#L420-L423).   It doesn't actually prompt the in app message though. It simply makes it so that _if_ the prime push event is sent, it prompts the user with the in app message before the push request alert.  That is my understanding based on reading the docs and from local testing.

2022-03-24 15:01 UTC, alexs-mparticle approved these changes

2022-03-28 14:08 UTC, alexs-mparticle approved these changes

2022-03-28 17:09 UTC, rmi22186 commented
This [approved PR was duplicated in our repo for Braze](https://github.com/mparticle-integrations/mparticle-javascript-integration-braze/pull/2), which we are moving over to in our transition from Appboy naming to Braze.  Closing this PR here since it has been merged there.

cc: @davidbielik

2022-03-28 17:09 UTC, closed without merging